### ISSUE TITLE
TODO for v2.0.0-rc1

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/kickoff-docker-php#24]
TODO for v2.0.0-rc1
- [x] Toolbox and PHP-FPM containers should use images (no more heavy Dockerfile)
- [x] PHP 7.1.7 -> 7.1.8
- [x] Add soap extension
- [x] Add [prestissimo](https://github.com/hirak/prestissimo)
- [x] Certifications path for environment <> `local`
- [x] Improve user issue workaround on Linux
- [x] Improve documentation (better explanations)
- [x] Improve Docker Sync: ignore some folders by default
- [x] Add Travis CI (Linux) and AppVeyor CI (Windows)

**Comment by gulien** [comment]
Closed by #29
